let name = prompt("Enter Name")
let age = prompt("Enter Age")
let work = prompt("Enter Company that you're working now")
console.log('Your name is ' + name)
console.log('Your age is ' + age)
console.log('Your work is ' + work)